workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "integration"
      when: always
    - when: never

stages:
  - test

test_scripts:
  stage: test
  image: python:3.12
  variables:
    PM4PY_DEFAULT_ENABLE_VISUALIZATIONS_VIEW: "False"
  before_script:
    - apt-get update -y
    - apt-get install -y graphviz
    - pip install -r requirements_stable.txt
  script:
    - cd tests
    - python execute_tests.py
  # If execute_tests.py returns non-zero, job fails.

example_scripts:
  stage: test
  image: python:3.12
  variables:
    PM4PY_DEFAULT_ENABLE_VISUALIZATIONS_VIEW: "False"
  before_script:
    - apt-get update -y
    - apt-get install -y graphviz
    - pip install -r requirements_stable.txt
    - pip install .
  script:
    - cd examples
    - python execute_everything.py
  # If execute_everything.py returns non-zero, job fails.
